# Generated by Django 3.2.16 on 2023-11-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Starwars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='episode_from',
        ),
        migrations.RemoveField(
            model_name='character',
            name='episode_to',
        ),
        migrations.AddField(
            model_name='character',
            name='starships',
            field=models.ManyToManyField(blank=True, to='Starwars.Starship'),
        ),
        migrations.AddField(
            model_name='starship',
            name='attack',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='starship',
            name='defend',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='starship',
            name='dodge',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
