# Generated by Django 3.2.16 on 2023-11-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Starwars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='episode_from',
        ),
        migrations.RemoveField(
            model_name='character',
            name='episode_to',
        ),
        migrations.AddField(
            model_name='character',
            name='starships',
            field=models.ManyToManyField(blank=True, to='Starwars.Starship'),
        ),
        migrations.AddField(
            model_name='starship',
            name='attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='starship',
            name='defend',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='starship',
            name='dodge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='episodes',
            field=models.ManyToManyField(blank=True, to='Starwars.Episode'),
        ),
    ]
