# Generated by Django 4.2.6 on 2023-12-04 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Starwars', '0002_auto_20231121_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='details',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='episode_from',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='episode_to',
        ),
        migrations.AddField(
            model_name='battle',
            name='player1_character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_character', to='Starwars.character'),
        ),
        migrations.AddField(
            model_name='battle',
            name='player1_starship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_starship', to='Starwars.starship'),
        ),
        migrations.AddField(
            model_name='battle',
            name='player2_character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_character', to='Starwars.character'),
        ),
        migrations.AddField(
            model_name='battle',
            name='player2_starship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_starship', to='Starwars.starship'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='won',
            field=models.CharField(max_length=1),
        ),
    ]
