# Generated by Django 3.2.16 on 2023-11-21 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Starwars', '0002_auto_20231121_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Starwars.character')),
                ('chosen_episode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Starwars.episode')),
                ('chosen_starship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Starwars.starship')),
            ],
        ),
    ]
