# Generated by Django 3.2.16 on 2023-11-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Starwars', '0002_auto_20231118_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starship',
            name='attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='starship',
            name='defend',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='starship',
            name='dodge',
            field=models.IntegerField(default=0),
        ),
    ]
