# Generated by Django 3.2.16 on 2023-11-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Starwars', '0003_auto_20231118_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='episodes',
            field=models.ManyToManyField(blank=True, to='Starwars.Episode'),
        ),
    ]
